name: CI workflow

on:
  workflow_dispatch:
  pull_request:
    branch:
      - main
  push:
    branch:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./web

jobs:
  tests:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
 
      - name: 'Install depandeancies'
        run: npn install

      - name: 'run tests'
        run: npm run test

  linter:
    name: 'Linter check'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: 'Install dependencies'
        run: npn install

      - name: 'Run linter'
        run: npx standard -v


